/**
 * Global Variables
 */
const PROJECT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_SECRET = 'XXXXXXXXXXXXXXXXXX';
const THERMOSTAT = 'XXXXXXXXXXXXXXXXXX';
const OPEN_WEATHER_ID = 'XXXXXXXXXXXXXXXXXX';
