/**
 * Global Variables
 * 
 * Do NOT publish this file, it contains several secrets
 */
const PROJECT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_SECRET = 'XXXXXXXXXXXXXXXXXX';
const OPEN_WEATHER_ID = 'XXXXXXXXXXXXXXXXXX';
const PARTICLE_DEVICE = 'XXXXXXXXXXXXXXXXXX';
const PARTICLE_ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXX';
const ZIP = 'XXXXXXXXXXXXXXXXXX';
// const WEATHER_STATION = 'XXXXXXXXXXXXXXXXXX';
const SHEET_NAME = 'XXXXXXXXXXXXXXXXXX';
const IFTTT_KEY = 'XXXXXXXXXXXXXXXXXX';
const IFTTT_NAME = 'XXXXXXXXXXXXXXXXXX';
